services:
  timescale:
    container_name: file-storage-timescale
    image: timescale/timescaledb-ha:pg18.1-ts2.24.0
    command: >
      postgres -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10
    environment:
      POSTGRES_USER: "anhle"
      POSTGRES_PASSWORD: "anhle"
      POSTGRES_DB: "file_storage"
      TZ: "UTC"
    ports:
      - "54321:5432"
    volumes:
      - ./tmp/postgres_data:/home/postgres/pgdata/data
    networks:
      - file-storage-network

  migrate:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    environment:
      - DB_URL=postgres://anhle:anhle@file-storage-timescale:5432/file_storage?sslmode=disable
    volumes:
      - ./internal/data/db/migrations/sql:/migrations/sql
    command: ["-path", "/migrations/sql", "up"]
    depends_on:
      - timescale
    networks:
      - file-storage-network

  # elasticsearch:
  #   container_name: file-storage-elasticsearch-local
  #   image: elasticsearch:9.2.0
  #   ports:
  #     - "9200:9200" # Rest
  #     - "9300:9300" # Cluster
  #   volumes:
  #     - ./tmp/es_data:/usr/share/elasticsearch/data
  #   environment:
  #     http.port: 9200
  #     transport.port: 9300
  #     discovery.type: single-node
  #     xpack.security.enabled: true
  #     xpack.security.http.ssl.enabled: false
  #     xpack.security.enrollment.enabled: true
  #     ELASTIC_PASSWORD: anhle # (build-in) user: elastic by default
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   networks:
  #     - file-storage-network

networks:
  file-storage-network:
    driver: bridge
