// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: m2m_auth/v1/auth.proto

package m2mv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	M2MAuthService_Login_FullMethodName = "/m2m_auth.v1.M2MAuthService/Login"
)

// M2MAuthServiceClient is the client API for M2MAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type M2MAuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type m2MAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewM2MAuthServiceClient(cc grpc.ClientConnInterface) M2MAuthServiceClient {
	return &m2MAuthServiceClient{cc}
}

func (c *m2MAuthServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, M2MAuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M2MAuthServiceServer is the server API for M2MAuthService service.
// All implementations must embed UnimplementedM2MAuthServiceServer
// for forward compatibility.
type M2MAuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	mustEmbedUnimplementedM2MAuthServiceServer()
}

// UnimplementedM2MAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedM2MAuthServiceServer struct{}

func (UnimplementedM2MAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedM2MAuthServiceServer) mustEmbedUnimplementedM2MAuthServiceServer() {}
func (UnimplementedM2MAuthServiceServer) testEmbeddedByValue()                        {}

// UnsafeM2MAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to M2MAuthServiceServer will
// result in compilation errors.
type UnsafeM2MAuthServiceServer interface {
	mustEmbedUnimplementedM2MAuthServiceServer()
}

func RegisterM2MAuthServiceServer(s grpc.ServiceRegistrar, srv M2MAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedM2MAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&M2MAuthService_ServiceDesc, srv)
}

func _M2MAuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MAuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: M2MAuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MAuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// M2MAuthService_ServiceDesc is the grpc.ServiceDesc for M2MAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var M2MAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "m2m_auth.v1.M2MAuthService",
	HandlerType: (*M2MAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _M2MAuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "m2m_auth/v1/auth.proto",
}
