// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: m2m_auth/v1/auth.proto

package m2mv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationM2MAuthServiceLogin = "/m2m_auth.v1.M2MAuthService/Login"

type M2MAuthServiceHTTPServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
}

func RegisterM2MAuthServiceHTTPServer(s *http.Server, srv M2MAuthServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/m2m/v1/auth/login", _M2MAuthService_Login0_HTTP_Handler(srv))
}

func _M2MAuthService_Login0_HTTP_Handler(srv M2MAuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationM2MAuthServiceLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

type M2MAuthServiceHTTPClient interface {
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
}

type M2MAuthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewM2MAuthServiceHTTPClient(client *http.Client) M2MAuthServiceHTTPClient {
	return &M2MAuthServiceHTTPClientImpl{client}
}

func (c *M2MAuthServiceHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/m2m/v1/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationM2MAuthServiceLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
