// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: m2m_auth/v1/auth.proto

package m2mv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_m2m_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m2m_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_m2m_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_m2m_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_m2m_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_m2m_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_m2m_auth_v1_auth_proto protoreflect.FileDescriptor

const file_m2m_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16m2m_auth/v1/auth.proto\x12\vm2m_auth.v1\x1a\x1cgoogle/api/annotations.proto\"P\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"N\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn2b\n" +
	"\x04Auth\x12Z\n" +
	"\x05Login\x12\x19.m2m_auth.v1.LoginRequest\x1a\x17.m2m_auth.v1.LoginReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/m2m/v1/auth/loginB\x1cZ\x1afile/api/m2m_auth/v1;m2mv1b\x06proto3"

var (
	file_m2m_auth_v1_auth_proto_rawDescOnce sync.Once
	file_m2m_auth_v1_auth_proto_rawDescData []byte
)

func file_m2m_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_m2m_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_m2m_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_m2m_auth_v1_auth_proto_rawDesc), len(file_m2m_auth_v1_auth_proto_rawDesc)))
	})
	return file_m2m_auth_v1_auth_proto_rawDescData
}

var file_m2m_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_m2m_auth_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: m2m_auth.v1.LoginRequest
	(*LoginReply)(nil),   // 1: m2m_auth.v1.LoginReply
}
var file_m2m_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: m2m_auth.v1.Auth.Login:input_type -> m2m_auth.v1.LoginRequest
	1, // 1: m2m_auth.v1.Auth.Login:output_type -> m2m_auth.v1.LoginReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_m2m_auth_v1_auth_proto_init() }
func file_m2m_auth_v1_auth_proto_init() {
	if File_m2m_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_m2m_auth_v1_auth_proto_rawDesc), len(file_m2m_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_m2m_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_m2m_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_m2m_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_m2m_auth_v1_auth_proto = out.File
	file_m2m_auth_v1_auth_proto_goTypes = nil
	file_m2m_auth_v1_auth_proto_depIdxs = nil
}
