// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: share/v1/share.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShareServiceCreateShareLink = "/api.share.v1.ShareService/CreateShareLink"
const OperationShareServiceListShareLinksByCreator = "/api.share.v1.ShareService/ListShareLinksByCreator"
const OperationShareServiceListShareLinksByResource = "/api.share.v1.ShareService/ListShareLinksByResource"
const OperationShareServiceResolveShareLink = "/api.share.v1.ShareService/ResolveShareLink"
const OperationShareServiceRevokeShareLink = "/api.share.v1.ShareService/RevokeShareLink"
const OperationShareServiceUpdateShareLink = "/api.share.v1.ShareService/UpdateShareLink"

type ShareServiceHTTPServer interface {
	// CreateShareLink 1. CREATE: Called by the owner to generate a link
	CreateShareLink(context.Context, *CreateShareLinkRequest) (*CreateShareLinkResponse, error)
	// ListShareLinksByCreator 3. LIST (GLOBAL): Called by the owner for their "My Links" dashboard
	ListShareLinksByCreator(context.Context, *ListShareLinksByCreatorRequest) (*ListShareLinksByCreatorResponse, error)
	// ListShareLinksByResource 4. LIST (LOCAL): Called by the owner to see who has access to a specific file/folder
	ListShareLinksByResource(context.Context, *ListShareLinksByResourceRequest) (*ListShareLinksByResourceResponse, error)
	// ResolveShareLink 2. RESOLVE: Called by the visitor when they click the URL (The Missing Endpoint)
	ResolveShareLink(context.Context, *ResolveShareLinkRequest) (*ResolveShareLinkResponse, error)
	// RevokeShareLink 6. DELETE: Called by the owner to kill the link
	RevokeShareLink(context.Context, *RevokeShareLinkRequest) (*RevokeShareLinkResponse, error)
	// UpdateShareLink 5. UPDATE: Called by the owner to change "viewer" to "editor"
	UpdateShareLink(context.Context, *UpdateShareLinkRequest) (*UpdateShareLinkResponse, error)
}

func RegisterShareServiceHTTPServer(s *http.Server, srv ShareServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/shares", _ShareService_CreateShareLink0_HTTP_Handler(srv))
	r.GET("/v1/shares/{link_token}", _ShareService_ResolveShareLink0_HTTP_Handler(srv))
	r.GET("/v1/shares/me", _ShareService_ListShareLinksByCreator0_HTTP_Handler(srv))
	r.GET("/v1/files/{resource_id}/shares", _ShareService_ListShareLinksByResource0_HTTP_Handler(srv))
	r.PATCH("/v1/shares/{link_token}", _ShareService_UpdateShareLink0_HTTP_Handler(srv))
	r.DELETE("/v1/shares/{link_token}", _ShareService_RevokeShareLink0_HTTP_Handler(srv))
}

func _ShareService_CreateShareLink0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShareLinkRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceCreateShareLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShareLink(ctx, req.(*CreateShareLinkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShareLinkResponse)
		return ctx.Result(200, reply)
	}
}

func _ShareService_ResolveShareLink0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveShareLinkRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceResolveShareLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveShareLink(ctx, req.(*ResolveShareLinkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveShareLinkResponse)
		return ctx.Result(200, reply)
	}
}

func _ShareService_ListShareLinksByCreator0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShareLinksByCreatorRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceListShareLinksByCreator)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShareLinksByCreator(ctx, req.(*ListShareLinksByCreatorRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShareLinksByCreatorResponse)
		return ctx.Result(200, reply)
	}
}

func _ShareService_ListShareLinksByResource0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShareLinksByResourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceListShareLinksByResource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShareLinksByResource(ctx, req.(*ListShareLinksByResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShareLinksByResourceResponse)
		return ctx.Result(200, reply)
	}
}

func _ShareService_UpdateShareLink0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateShareLinkRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceUpdateShareLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateShareLink(ctx, req.(*UpdateShareLinkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateShareLinkResponse)
		return ctx.Result(200, reply)
	}
}

func _ShareService_RevokeShareLink0_HTTP_Handler(srv ShareServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeShareLinkRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareServiceRevokeShareLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeShareLink(ctx, req.(*RevokeShareLinkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeShareLinkResponse)
		return ctx.Result(200, reply)
	}
}

type ShareServiceHTTPClient interface {
	// CreateShareLink 1. CREATE: Called by the owner to generate a link
	CreateShareLink(ctx context.Context, req *CreateShareLinkRequest, opts ...http.CallOption) (rsp *CreateShareLinkResponse, err error)
	// ListShareLinksByCreator 3. LIST (GLOBAL): Called by the owner for their "My Links" dashboard
	ListShareLinksByCreator(ctx context.Context, req *ListShareLinksByCreatorRequest, opts ...http.CallOption) (rsp *ListShareLinksByCreatorResponse, err error)
	// ListShareLinksByResource 4. LIST (LOCAL): Called by the owner to see who has access to a specific file/folder
	ListShareLinksByResource(ctx context.Context, req *ListShareLinksByResourceRequest, opts ...http.CallOption) (rsp *ListShareLinksByResourceResponse, err error)
	// ResolveShareLink 2. RESOLVE: Called by the visitor when they click the URL (The Missing Endpoint)
	ResolveShareLink(ctx context.Context, req *ResolveShareLinkRequest, opts ...http.CallOption) (rsp *ResolveShareLinkResponse, err error)
	// RevokeShareLink 6. DELETE: Called by the owner to kill the link
	RevokeShareLink(ctx context.Context, req *RevokeShareLinkRequest, opts ...http.CallOption) (rsp *RevokeShareLinkResponse, err error)
	// UpdateShareLink 5. UPDATE: Called by the owner to change "viewer" to "editor"
	UpdateShareLink(ctx context.Context, req *UpdateShareLinkRequest, opts ...http.CallOption) (rsp *UpdateShareLinkResponse, err error)
}

type ShareServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShareServiceHTTPClient(client *http.Client) ShareServiceHTTPClient {
	return &ShareServiceHTTPClientImpl{client}
}

// CreateShareLink 1. CREATE: Called by the owner to generate a link
func (c *ShareServiceHTTPClientImpl) CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...http.CallOption) (*CreateShareLinkResponse, error) {
	var out CreateShareLinkResponse
	pattern := "/v1/shares"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShareServiceCreateShareLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListShareLinksByCreator 3. LIST (GLOBAL): Called by the owner for their "My Links" dashboard
func (c *ShareServiceHTTPClientImpl) ListShareLinksByCreator(ctx context.Context, in *ListShareLinksByCreatorRequest, opts ...http.CallOption) (*ListShareLinksByCreatorResponse, error) {
	var out ListShareLinksByCreatorResponse
	pattern := "/v1/shares/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareServiceListShareLinksByCreator))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListShareLinksByResource 4. LIST (LOCAL): Called by the owner to see who has access to a specific file/folder
func (c *ShareServiceHTTPClientImpl) ListShareLinksByResource(ctx context.Context, in *ListShareLinksByResourceRequest, opts ...http.CallOption) (*ListShareLinksByResourceResponse, error) {
	var out ListShareLinksByResourceResponse
	pattern := "/v1/files/{resource_id}/shares"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareServiceListShareLinksByResource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveShareLink 2. RESOLVE: Called by the visitor when they click the URL (The Missing Endpoint)
func (c *ShareServiceHTTPClientImpl) ResolveShareLink(ctx context.Context, in *ResolveShareLinkRequest, opts ...http.CallOption) (*ResolveShareLinkResponse, error) {
	var out ResolveShareLinkResponse
	pattern := "/v1/shares/{link_token}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareServiceResolveShareLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeShareLink 6. DELETE: Called by the owner to kill the link
func (c *ShareServiceHTTPClientImpl) RevokeShareLink(ctx context.Context, in *RevokeShareLinkRequest, opts ...http.CallOption) (*RevokeShareLinkResponse, error) {
	var out RevokeShareLinkResponse
	pattern := "/v1/shares/{link_token}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareServiceRevokeShareLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateShareLink 5. UPDATE: Called by the owner to change "viewer" to "editor"
func (c *ShareServiceHTTPClientImpl) UpdateShareLink(ctx context.Context, in *UpdateShareLinkRequest, opts ...http.CallOption) (*UpdateShareLinkResponse, error) {
	var out UpdateShareLinkResponse
	pattern := "/v1/shares/{link_token}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShareServiceUpdateShareLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
