// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: share/v1/share.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- CREATE ---
type CreateShareLinkRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType    string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`          // "file" or "folder"
	PermissionLevel string                 `protobuf:"bytes,3,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"` // "viewer" or "editor"
	ExpiresAt       string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                   // Optional ISO8601 string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShareLinkRequest) Reset() {
	*x = CreateShareLinkRequest{}
	mi := &file_share_v1_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkRequest) ProtoMessage() {}

func (x *CreateShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShareLinkRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateShareLinkRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreateShareLinkRequest) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *CreateShareLinkRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,2,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"` // Helpful for the frontend (e.g. "https://socialfi.com/shared/xyz")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareLinkResponse) Reset() {
	*x = CreateShareLinkResponse{}
	mi := &file_share_v1_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkResponse) ProtoMessage() {}

func (x *CreateShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShareLinkResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *CreateShareLinkResponse) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

// --- RESOLVE (Visitor) ---
type ResolveShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"` // Extracted from URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShareLinkRequest) Reset() {
	*x = ResolveShareLinkRequest{}
	mi := &file_share_v1_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShareLinkRequest) ProtoMessage() {}

func (x *ResolveShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShareLinkRequest.ProtoReflect.Descriptor instead.
func (*ResolveShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveShareLinkRequest) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

type ResolveShareLinkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType    string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	PermissionLevel string                 `protobuf:"bytes,3,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatorId       string                 `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveShareLinkResponse) Reset() {
	*x = ResolveShareLinkResponse{}
	mi := &file_share_v1_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShareLinkResponse) ProtoMessage() {}

func (x *ResolveShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShareLinkResponse.ProtoReflect.Descriptor instead.
func (*ResolveShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveShareLinkResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResolveShareLinkResponse) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResolveShareLinkResponse) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *ResolveShareLinkResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ResolveShareLinkResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

// --- LIST SHARES ---
type ShareLinkInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LinkToken       string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`
	PermissionLevel string                 `protobuf:"bytes,2,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ShareUrl        string                 `protobuf:"bytes,4,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShareLinkInfo) Reset() {
	*x = ShareLinkInfo{}
	mi := &file_share_v1_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareLinkInfo) ProtoMessage() {}

func (x *ShareLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareLinkInfo.ProtoReflect.Descriptor instead.
func (*ShareLinkInfo) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{4}
}

func (x *ShareLinkInfo) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *ShareLinkInfo) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *ShareLinkInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShareLinkInfo) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

type ListShareLinksByCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShareLinksByCreatorRequest) Reset() {
	*x = ListShareLinksByCreatorRequest{}
	mi := &file_share_v1_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShareLinksByCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShareLinksByCreatorRequest) ProtoMessage() {}

func (x *ListShareLinksByCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShareLinksByCreatorRequest.ProtoReflect.Descriptor instead.
func (*ListShareLinksByCreatorRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{5}
}

func (x *ListShareLinksByCreatorRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListShareLinksByCreatorRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListShareLinksByCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShareLinkInfo       `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShareLinksByCreatorResponse) Reset() {
	*x = ListShareLinksByCreatorResponse{}
	mi := &file_share_v1_share_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShareLinksByCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShareLinksByCreatorResponse) ProtoMessage() {}

func (x *ListShareLinksByCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShareLinksByCreatorResponse.ProtoReflect.Descriptor instead.
func (*ListShareLinksByCreatorResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{6}
}

func (x *ListShareLinksByCreatorResponse) GetLinks() []*ShareLinkInfo {
	if x != nil {
		return x.Links
	}
	return nil
}

type ListShareLinksByResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // Extracted from URL
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShareLinksByResourceRequest) Reset() {
	*x = ListShareLinksByResourceRequest{}
	mi := &file_share_v1_share_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShareLinksByResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShareLinksByResourceRequest) ProtoMessage() {}

func (x *ListShareLinksByResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShareLinksByResourceRequest.ProtoReflect.Descriptor instead.
func (*ListShareLinksByResourceRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{7}
}

func (x *ListShareLinksByResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ListShareLinksByResourceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListShareLinksByResourceRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListShareLinksByResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShareLinkInfo       `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShareLinksByResourceResponse) Reset() {
	*x = ListShareLinksByResourceResponse{}
	mi := &file_share_v1_share_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShareLinksByResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShareLinksByResourceResponse) ProtoMessage() {}

func (x *ListShareLinksByResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShareLinksByResourceResponse.ProtoReflect.Descriptor instead.
func (*ListShareLinksByResourceResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{8}
}

func (x *ListShareLinksByResourceResponse) GetLinks() []*ShareLinkInfo {
	if x != nil {
		return x.Links
	}
	return nil
}

// --- UPDATE & REVOKE ---
type UpdateShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`             // Extracted from URL
	NewPermission string                 `protobuf:"bytes,2,opt,name=new_permission,json=newPermission,proto3" json:"new_permission,omitempty"` // e.g., "editor"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareLinkRequest) Reset() {
	*x = UpdateShareLinkRequest{}
	mi := &file_share_v1_share_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareLinkRequest) ProtoMessage() {}

func (x *UpdateShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateShareLinkRequest) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *UpdateShareLinkRequest) GetNewPermission() string {
	if x != nil {
		return x.NewPermission
	}
	return ""
}

type UpdateShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareLinkResponse) Reset() {
	*x = UpdateShareLinkResponse{}
	mi := &file_share_v1_share_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareLinkResponse) ProtoMessage() {}

func (x *UpdateShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateShareLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkToken     string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"` // Extracted from URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareLinkRequest) Reset() {
	*x = RevokeShareLinkRequest{}
	mi := &file_share_v1_share_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareLinkRequest) ProtoMessage() {}

func (x *RevokeShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareLinkRequest.ProtoReflect.Descriptor instead.
func (*RevokeShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeShareLinkRequest) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

type RevokeShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareLinkResponse) Reset() {
	*x = RevokeShareLinkResponse{}
	mi := &file_share_v1_share_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareLinkResponse) ProtoMessage() {}

func (x *RevokeShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_share_v1_share_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareLinkResponse.ProtoReflect.Descriptor instead.
func (*RevokeShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_share_v1_share_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeShareLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_share_v1_share_proto protoreflect.FileDescriptor

const file_share_v1_share_proto_rawDesc = "" +
	"\n" +
	"\x14share/v1/share.proto\x12\fapi.share.v1\x1a\x1cgoogle/api/annotations.proto\"\xa8\x01\n" +
	"\x16CreateShareLinkRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12)\n" +
	"\x10permission_level\x18\x03 \x01(\tR\x0fpermissionLevel\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"U\n" +
	"\x17CreateShareLinkResponse\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\x12\x1b\n" +
	"\tshare_url\x18\x02 \x01(\tR\bshareUrl\"8\n" +
	"\x17ResolveShareLinkRequest\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\"\xc9\x01\n" +
	"\x18ResolveShareLinkResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12)\n" +
	"\x10permission_level\x18\x03 \x01(\tR\x0fpermissionLevel\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\"\x95\x01\n" +
	"\rShareLinkInfo\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\x12)\n" +
	"\x10permission_level\x18\x02 \x01(\tR\x0fpermissionLevel\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tshare_url\x18\x04 \x01(\tR\bshareUrl\"N\n" +
	"\x1eListShareLinksByCreatorRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"T\n" +
	"\x1fListShareLinksByCreatorResponse\x121\n" +
	"\x05links\x18\x01 \x03(\v2\x1b.api.share.v1.ShareLinkInfoR\x05links\"p\n" +
	"\x1fListShareLinksByResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"U\n" +
	" ListShareLinksByResourceResponse\x121\n" +
	"\x05links\x18\x01 \x03(\v2\x1b.api.share.v1.ShareLinkInfoR\x05links\"^\n" +
	"\x16UpdateShareLinkRequest\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\x12%\n" +
	"\x0enew_permission\x18\x02 \x01(\tR\rnewPermission\"3\n" +
	"\x17UpdateShareLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x16RevokeShareLinkRequest\x12\x1d\n" +
	"\n" +
	"link_token\x18\x01 \x01(\tR\tlinkToken\"3\n" +
	"\x17RevokeShareLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc4\x06\n" +
	"\fShareService\x12u\n" +
	"\x0fCreateShareLink\x12$.api.share.v1.CreateShareLinkRequest\x1a%.api.share.v1.CreateShareLinkResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/shares\x12\x82\x01\n" +
	"\x10ResolveShareLink\x12%.api.share.v1.ResolveShareLinkRequest\x1a&.api.share.v1.ResolveShareLinkResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/shares/{link_token}\x12\x8d\x01\n" +
	"\x17ListShareLinksByCreator\x12,.api.share.v1.ListShareLinksByCreatorRequest\x1a-.api.share.v1.ListShareLinksByCreatorResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/shares/me\x12\xa1\x01\n" +
	"\x18ListShareLinksByResource\x12-.api.share.v1.ListShareLinksByResourceRequest\x1a..api.share.v1.ListShareLinksByResourceResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/files/{resource_id}/shares\x12\x82\x01\n" +
	"\x0fUpdateShareLink\x12$.api.share.v1.UpdateShareLinkRequest\x1a%.api.share.v1.UpdateShareLinkResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/shares/{link_token}\x12\x7f\n" +
	"\x0fRevokeShareLink\x12$.api.share.v1.RevokeShareLinkRequest\x1a%.api.share.v1.RevokeShareLinkResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/shares/{link_token}B\x16Z\x14file/api/share/v1;v1b\x06proto3"

var (
	file_share_v1_share_proto_rawDescOnce sync.Once
	file_share_v1_share_proto_rawDescData []byte
)

func file_share_v1_share_proto_rawDescGZIP() []byte {
	file_share_v1_share_proto_rawDescOnce.Do(func() {
		file_share_v1_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_share_v1_share_proto_rawDesc), len(file_share_v1_share_proto_rawDesc)))
	})
	return file_share_v1_share_proto_rawDescData
}

var file_share_v1_share_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_share_v1_share_proto_goTypes = []any{
	(*CreateShareLinkRequest)(nil),           // 0: api.share.v1.CreateShareLinkRequest
	(*CreateShareLinkResponse)(nil),          // 1: api.share.v1.CreateShareLinkResponse
	(*ResolveShareLinkRequest)(nil),          // 2: api.share.v1.ResolveShareLinkRequest
	(*ResolveShareLinkResponse)(nil),         // 3: api.share.v1.ResolveShareLinkResponse
	(*ShareLinkInfo)(nil),                    // 4: api.share.v1.ShareLinkInfo
	(*ListShareLinksByCreatorRequest)(nil),   // 5: api.share.v1.ListShareLinksByCreatorRequest
	(*ListShareLinksByCreatorResponse)(nil),  // 6: api.share.v1.ListShareLinksByCreatorResponse
	(*ListShareLinksByResourceRequest)(nil),  // 7: api.share.v1.ListShareLinksByResourceRequest
	(*ListShareLinksByResourceResponse)(nil), // 8: api.share.v1.ListShareLinksByResourceResponse
	(*UpdateShareLinkRequest)(nil),           // 9: api.share.v1.UpdateShareLinkRequest
	(*UpdateShareLinkResponse)(nil),          // 10: api.share.v1.UpdateShareLinkResponse
	(*RevokeShareLinkRequest)(nil),           // 11: api.share.v1.RevokeShareLinkRequest
	(*RevokeShareLinkResponse)(nil),          // 12: api.share.v1.RevokeShareLinkResponse
}
var file_share_v1_share_proto_depIdxs = []int32{
	4,  // 0: api.share.v1.ListShareLinksByCreatorResponse.links:type_name -> api.share.v1.ShareLinkInfo
	4,  // 1: api.share.v1.ListShareLinksByResourceResponse.links:type_name -> api.share.v1.ShareLinkInfo
	0,  // 2: api.share.v1.ShareService.CreateShareLink:input_type -> api.share.v1.CreateShareLinkRequest
	2,  // 3: api.share.v1.ShareService.ResolveShareLink:input_type -> api.share.v1.ResolveShareLinkRequest
	5,  // 4: api.share.v1.ShareService.ListShareLinksByCreator:input_type -> api.share.v1.ListShareLinksByCreatorRequest
	7,  // 5: api.share.v1.ShareService.ListShareLinksByResource:input_type -> api.share.v1.ListShareLinksByResourceRequest
	9,  // 6: api.share.v1.ShareService.UpdateShareLink:input_type -> api.share.v1.UpdateShareLinkRequest
	11, // 7: api.share.v1.ShareService.RevokeShareLink:input_type -> api.share.v1.RevokeShareLinkRequest
	1,  // 8: api.share.v1.ShareService.CreateShareLink:output_type -> api.share.v1.CreateShareLinkResponse
	3,  // 9: api.share.v1.ShareService.ResolveShareLink:output_type -> api.share.v1.ResolveShareLinkResponse
	6,  // 10: api.share.v1.ShareService.ListShareLinksByCreator:output_type -> api.share.v1.ListShareLinksByCreatorResponse
	8,  // 11: api.share.v1.ShareService.ListShareLinksByResource:output_type -> api.share.v1.ListShareLinksByResourceResponse
	10, // 12: api.share.v1.ShareService.UpdateShareLink:output_type -> api.share.v1.UpdateShareLinkResponse
	12, // 13: api.share.v1.ShareService.RevokeShareLink:output_type -> api.share.v1.RevokeShareLinkResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_share_v1_share_proto_init() }
func file_share_v1_share_proto_init() {
	if File_share_v1_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_share_v1_share_proto_rawDesc), len(file_share_v1_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_share_v1_share_proto_goTypes,
		DependencyIndexes: file_share_v1_share_proto_depIdxs,
		MessageInfos:      file_share_v1_share_proto_msgTypes,
	}.Build()
	File_share_v1_share_proto = out.File
	file_share_v1_share_proto_goTypes = nil
	file_share_v1_share_proto_depIdxs = nil
}
