// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: share/v1/share.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShareService_CreateShareLink_FullMethodName          = "/api.share.v1.ShareService/CreateShareLink"
	ShareService_ResolveShareLink_FullMethodName         = "/api.share.v1.ShareService/ResolveShareLink"
	ShareService_ListShareLinksByCreator_FullMethodName  = "/api.share.v1.ShareService/ListShareLinksByCreator"
	ShareService_ListShareLinksByResource_FullMethodName = "/api.share.v1.ShareService/ListShareLinksByResource"
	ShareService_UpdateShareLink_FullMethodName          = "/api.share.v1.ShareService/UpdateShareLink"
	ShareService_RevokeShareLink_FullMethodName          = "/api.share.v1.ShareService/RevokeShareLink"
)

// ShareServiceClient is the client API for ShareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =====================================================================
// SHARE SERVICE
// =====================================================================
type ShareServiceClient interface {
	// 1. CREATE: Called by the owner to generate a link
	CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*CreateShareLinkResponse, error)
	// 2. RESOLVE: Called by the visitor when they click the URL (The Missing Endpoint)
	ResolveShareLink(ctx context.Context, in *ResolveShareLinkRequest, opts ...grpc.CallOption) (*ResolveShareLinkResponse, error)
	// 3. LIST (GLOBAL): Called by the owner for their "My Links" dashboard
	ListShareLinksByCreator(ctx context.Context, in *ListShareLinksByCreatorRequest, opts ...grpc.CallOption) (*ListShareLinksByCreatorResponse, error)
	// 4. LIST (LOCAL): Called by the owner to see who has access to a specific file/folder
	ListShareLinksByResource(ctx context.Context, in *ListShareLinksByResourceRequest, opts ...grpc.CallOption) (*ListShareLinksByResourceResponse, error)
	// 5. UPDATE: Called by the owner to change "viewer" to "editor"
	UpdateShareLink(ctx context.Context, in *UpdateShareLinkRequest, opts ...grpc.CallOption) (*UpdateShareLinkResponse, error)
	// 6. DELETE: Called by the owner to kill the link
	RevokeShareLink(ctx context.Context, in *RevokeShareLinkRequest, opts ...grpc.CallOption) (*RevokeShareLinkResponse, error)
}

type shareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShareServiceClient(cc grpc.ClientConnInterface) ShareServiceClient {
	return &shareServiceClient{cc}
}

func (c *shareServiceClient) CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*CreateShareLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareLinkResponse)
	err := c.cc.Invoke(ctx, ShareService_CreateShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ResolveShareLink(ctx context.Context, in *ResolveShareLinkRequest, opts ...grpc.CallOption) (*ResolveShareLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveShareLinkResponse)
	err := c.cc.Invoke(ctx, ShareService_ResolveShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ListShareLinksByCreator(ctx context.Context, in *ListShareLinksByCreatorRequest, opts ...grpc.CallOption) (*ListShareLinksByCreatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShareLinksByCreatorResponse)
	err := c.cc.Invoke(ctx, ShareService_ListShareLinksByCreator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ListShareLinksByResource(ctx context.Context, in *ListShareLinksByResourceRequest, opts ...grpc.CallOption) (*ListShareLinksByResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShareLinksByResourceResponse)
	err := c.cc.Invoke(ctx, ShareService_ListShareLinksByResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UpdateShareLink(ctx context.Context, in *UpdateShareLinkRequest, opts ...grpc.CallOption) (*UpdateShareLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShareLinkResponse)
	err := c.cc.Invoke(ctx, ShareService_UpdateShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) RevokeShareLink(ctx context.Context, in *RevokeShareLinkRequest, opts ...grpc.CallOption) (*RevokeShareLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeShareLinkResponse)
	err := c.cc.Invoke(ctx, ShareService_RevokeShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShareServiceServer is the server API for ShareService service.
// All implementations must embed UnimplementedShareServiceServer
// for forward compatibility.
//
// =====================================================================
// SHARE SERVICE
// =====================================================================
type ShareServiceServer interface {
	// 1. CREATE: Called by the owner to generate a link
	CreateShareLink(context.Context, *CreateShareLinkRequest) (*CreateShareLinkResponse, error)
	// 2. RESOLVE: Called by the visitor when they click the URL (The Missing Endpoint)
	ResolveShareLink(context.Context, *ResolveShareLinkRequest) (*ResolveShareLinkResponse, error)
	// 3. LIST (GLOBAL): Called by the owner for their "My Links" dashboard
	ListShareLinksByCreator(context.Context, *ListShareLinksByCreatorRequest) (*ListShareLinksByCreatorResponse, error)
	// 4. LIST (LOCAL): Called by the owner to see who has access to a specific file/folder
	ListShareLinksByResource(context.Context, *ListShareLinksByResourceRequest) (*ListShareLinksByResourceResponse, error)
	// 5. UPDATE: Called by the owner to change "viewer" to "editor"
	UpdateShareLink(context.Context, *UpdateShareLinkRequest) (*UpdateShareLinkResponse, error)
	// 6. DELETE: Called by the owner to kill the link
	RevokeShareLink(context.Context, *RevokeShareLinkRequest) (*RevokeShareLinkResponse, error)
	mustEmbedUnimplementedShareServiceServer()
}

// UnimplementedShareServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShareServiceServer struct{}

func (UnimplementedShareServiceServer) CreateShareLink(context.Context, *CreateShareLinkRequest) (*CreateShareLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShareLink not implemented")
}
func (UnimplementedShareServiceServer) ResolveShareLink(context.Context, *ResolveShareLinkRequest) (*ResolveShareLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveShareLink not implemented")
}
func (UnimplementedShareServiceServer) ListShareLinksByCreator(context.Context, *ListShareLinksByCreatorRequest) (*ListShareLinksByCreatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShareLinksByCreator not implemented")
}
func (UnimplementedShareServiceServer) ListShareLinksByResource(context.Context, *ListShareLinksByResourceRequest) (*ListShareLinksByResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShareLinksByResource not implemented")
}
func (UnimplementedShareServiceServer) UpdateShareLink(context.Context, *UpdateShareLinkRequest) (*UpdateShareLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShareLink not implemented")
}
func (UnimplementedShareServiceServer) RevokeShareLink(context.Context, *RevokeShareLinkRequest) (*RevokeShareLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeShareLink not implemented")
}
func (UnimplementedShareServiceServer) mustEmbedUnimplementedShareServiceServer() {}
func (UnimplementedShareServiceServer) testEmbeddedByValue()                      {}

// UnsafeShareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShareServiceServer will
// result in compilation errors.
type UnsafeShareServiceServer interface {
	mustEmbedUnimplementedShareServiceServer()
}

func RegisterShareServiceServer(s grpc.ServiceRegistrar, srv ShareServiceServer) {
	// If the following call panics, it indicates UnimplementedShareServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShareService_ServiceDesc, srv)
}

func _ShareService_CreateShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CreateShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_CreateShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CreateShareLink(ctx, req.(*CreateShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ResolveShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ResolveShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_ResolveShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ResolveShareLink(ctx, req.(*ResolveShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ListShareLinksByCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShareLinksByCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ListShareLinksByCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_ListShareLinksByCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ListShareLinksByCreator(ctx, req.(*ListShareLinksByCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ListShareLinksByResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShareLinksByResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ListShareLinksByResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_ListShareLinksByResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ListShareLinksByResource(ctx, req.(*ListShareLinksByResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UpdateShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UpdateShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_UpdateShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UpdateShareLink(ctx, req.(*UpdateShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_RevokeShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).RevokeShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_RevokeShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).RevokeShareLink(ctx, req.(*RevokeShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShareService_ServiceDesc is the grpc.ServiceDesc for ShareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.share.v1.ShareService",
	HandlerType: (*ShareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShareLink",
			Handler:    _ShareService_CreateShareLink_Handler,
		},
		{
			MethodName: "ResolveShareLink",
			Handler:    _ShareService_ResolveShareLink_Handler,
		},
		{
			MethodName: "ListShareLinksByCreator",
			Handler:    _ShareService_ListShareLinksByCreator_Handler,
		},
		{
			MethodName: "ListShareLinksByResource",
			Handler:    _ShareService_ListShareLinksByResource_Handler,
		},
		{
			MethodName: "UpdateShareLink",
			Handler:    _ShareService_UpdateShareLink_Handler,
		},
		{
			MethodName: "RevokeShareLink",
			Handler:    _ShareService_RevokeShareLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "share/v1/share.proto",
}
