syntax="proto3";

package file.v1;

import "google/api/annotations.proto";

option go_package = "file/api/file/v1";

service FileService {
    rpc CreateFile(CreateFileRequest) returns (CreateFileResponse) {
        option (google.api.http) = {
            post: "/v1/files/create"
            body: "*"
        };
    }
}

message CreateFileRequest {
    string name = 1;
    string parent_id = 2;      // UUID where this file is placed, empty for root
    int64 file_size = 3;
    string file_type = 4;
    string file_ext = 5;
    string file_mime_type = 6;
    string file_hash = 7;      // Can be calculated on client side for dedup logic
    string file_video_resolution = 8;
    string status = 9;
}

message CreateFileResponse {
    string id = 1;
}
