syntax="proto3";

package file.v1;

import "google/api/annotations.proto";

option go_package = "file/api/file/v1";

service FileService {
    rpc CreateFile(CreateFileRequest) returns (CreateFileReply) {
        option (google.api.http) = {
            post: "/v1/files/create"
            body: "*"
        };
    }
    rpc GetUploadUrl(GetUploadUrlRequest) returns (GetUploadUrlReply) {
        option (google.api.http) = {
            get: "/v1/files/upload-url"
        };
    }
    rpc GetDownloadUrl(GetDownloadUrlRequest) returns (GetDownloadUrlReply) {
        option (google.api.http) = {
            get: "/v1/files/{id}/download-url"
        };
    }
    rpc GetFile(GetFileRequest) returns (GetFileReply) {
        option (google.api.http) = {
            get: "/v1/files/{id}"
        };
    }
}

message CreateFileRequest {
    string name = 1;
    string parent_id = 2;      // UUID where this file is placed, empty for root
    int64 file_size = 3;
    string file_type = 4;
    string file_ext = 5;
    string file_mime_type = 6;
    string file_hash = 7;      // Can be calculated on client side for dedup logic
    string file_video_resolution = 8;
    string status = 9;
    bool is_folder = 10;
}

message CreateFileReply {
    string id = 1;
}

message GetUploadUrlRequest {
    string name = 1;
    int64 file_size = 2;
    string file_mime_type = 3;
    string file_hash = 4;
}

message GetUploadUrlReply {
    string upload_url = 1;
    string file_id = 2;
}

message GetDownloadUrlRequest {
    string id = 1;
}

message GetDownloadUrlReply {
    string download_url = 1;
}

message GetFileRequest {
    string id = 1;
}

message GetFileReply {
    string id = 1;
    string name = 2;
    int64 file_size = 3;
    string file_mime_type = 4;
    bool is_folder = 5;
    string created_at = 6;
    string updated_at = 7;
}
