// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: subscription/v1/subscription.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Subscription) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Subscription) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

type GetUserSubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionReply) Reset() {
	*x = GetUserSubscriptionReply{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionReply) ProtoMessage() {}

func (x *GetUserSubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionReply.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserSubscriptionReply) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type SubscribePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePlanRequest) Reset() {
	*x = SubscribePlanRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePlanRequest) ProtoMessage() {}

func (x *SubscribePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePlanRequest.ProtoReflect.Descriptor instead.
func (*SubscribePlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribePlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type SubscribePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePlanReply) Reset() {
	*x = SubscribePlanReply{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePlanReply) ProtoMessage() {}

func (x *SubscribePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePlanReply.ProtoReflect.Descriptor instead.
func (*SubscribePlanReply) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribePlanReply) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type ListUserSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSubscriptionsRequest) Reset() {
	*x = ListUserSubscriptionsRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSubscriptionsRequest) ProtoMessage() {}

func (x *ListUserSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{5}
}

type ListUserSubscriptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSubscriptionsReply) Reset() {
	*x = ListUserSubscriptionsReply{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSubscriptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSubscriptionsReply) ProtoMessage() {}

func (x *ListUserSubscriptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSubscriptionsReply.ProtoReflect.Descriptor instead.
func (*ListUserSubscriptionsReply) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserSubscriptionsReply) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"\"subscription/v1/subscription.proto\x12\x13api.subscription.v1\x1a\x1cgoogle/api/annotations.proto\"\xe4\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\tR\texpiredAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x1c\n" +
	"\x1aGetUserSubscriptionRequest\"a\n" +
	"\x18GetUserSubscriptionReply\x12E\n" +
	"\fsubscription\x18\x01 \x01(\v2!.api.subscription.v1.SubscriptionR\fsubscription\"/\n" +
	"\x14SubscribePlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"[\n" +
	"\x12SubscribePlanReply\x12E\n" +
	"\fsubscription\x18\x01 \x01(\v2!.api.subscription.v1.SubscriptionR\fsubscription\"\x1e\n" +
	"\x1cListUserSubscriptionsRequest\"e\n" +
	"\x1aListUserSubscriptionsReply\x12G\n" +
	"\rsubscriptions\x18\x01 \x03(\v2!.api.subscription.v1.SubscriptionR\rsubscriptions2\xc8\x03\n" +
	"\x13SubscriptionService\x12\x93\x01\n" +
	"\x13GetUserSubscription\x12/.api.subscription.v1.GetUserSubscriptionRequest\x1a-.api.subscription.v1.GetUserSubscriptionReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/subscriptions/me\x12\x81\x01\n" +
	"\rSubscribePlan\x12).api.subscription.v1.SubscribePlanRequest\x1a'.api.subscription.v1.SubscribePlanReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/subscriptions\x12\x96\x01\n" +
	"\x15ListUserSubscriptions\x121.api.subscription.v1.ListUserSubscriptionsRequest\x1a/.api.subscription.v1.ListUserSubscriptionsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/subscriptionsB\x1dZ\x1bfile/api/subscription/v1;v1b\x06proto3"

var (
	file_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_subscription_v1_subscription_proto_rawDescData []byte
)

func file_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_subscription_v1_subscription_proto_rawDescData
}

var file_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_subscription_v1_subscription_proto_goTypes = []any{
	(*Subscription)(nil),                 // 0: api.subscription.v1.Subscription
	(*GetUserSubscriptionRequest)(nil),   // 1: api.subscription.v1.GetUserSubscriptionRequest
	(*GetUserSubscriptionReply)(nil),     // 2: api.subscription.v1.GetUserSubscriptionReply
	(*SubscribePlanRequest)(nil),         // 3: api.subscription.v1.SubscribePlanRequest
	(*SubscribePlanReply)(nil),           // 4: api.subscription.v1.SubscribePlanReply
	(*ListUserSubscriptionsRequest)(nil), // 5: api.subscription.v1.ListUserSubscriptionsRequest
	(*ListUserSubscriptionsReply)(nil),   // 6: api.subscription.v1.ListUserSubscriptionsReply
}
var file_subscription_v1_subscription_proto_depIdxs = []int32{
	0, // 0: api.subscription.v1.GetUserSubscriptionReply.subscription:type_name -> api.subscription.v1.Subscription
	0, // 1: api.subscription.v1.SubscribePlanReply.subscription:type_name -> api.subscription.v1.Subscription
	0, // 2: api.subscription.v1.ListUserSubscriptionsReply.subscriptions:type_name -> api.subscription.v1.Subscription
	1, // 3: api.subscription.v1.SubscriptionService.GetUserSubscription:input_type -> api.subscription.v1.GetUserSubscriptionRequest
	3, // 4: api.subscription.v1.SubscriptionService.SubscribePlan:input_type -> api.subscription.v1.SubscribePlanRequest
	5, // 5: api.subscription.v1.SubscriptionService.ListUserSubscriptions:input_type -> api.subscription.v1.ListUserSubscriptionsRequest
	2, // 6: api.subscription.v1.SubscriptionService.GetUserSubscription:output_type -> api.subscription.v1.GetUserSubscriptionReply
	4, // 7: api.subscription.v1.SubscriptionService.SubscribePlan:output_type -> api.subscription.v1.SubscribePlanReply
	6, // 8: api.subscription.v1.SubscriptionService.ListUserSubscriptions:output_type -> api.subscription.v1.ListUserSubscriptionsReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subscription_v1_subscription_proto_init() }
func file_subscription_v1_subscription_proto_init() {
	if File_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_subscription_v1_subscription_proto = out.File
	file_subscription_v1_subscription_proto_goTypes = nil
	file_subscription_v1_subscription_proto_depIdxs = nil
}
