// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: subscription/v1/subscription.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSubscriptionServiceGetUserSubscription = "/api.subscription.v1.SubscriptionService/GetUserSubscription"
const OperationSubscriptionServiceListUserSubscriptions = "/api.subscription.v1.SubscriptionService/ListUserSubscriptions"
const OperationSubscriptionServiceSubscribePlan = "/api.subscription.v1.SubscriptionService/SubscribePlan"

type SubscriptionServiceHTTPServer interface {
	GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*GetUserSubscriptionResponse, error)
	ListUserSubscriptions(context.Context, *ListUserSubscriptionsRequest) (*ListUserSubscriptionsResponse, error)
	SubscribePlan(context.Context, *SubscribePlanRequest) (*SubscribePlanResponse, error)
}

func RegisterSubscriptionServiceHTTPServer(s *http.Server, srv SubscriptionServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/subscriptions/me", _SubscriptionService_GetUserSubscription0_HTTP_Handler(srv))
	r.POST("/v1/subscriptions", _SubscriptionService_SubscribePlan0_HTTP_Handler(srv))
	r.GET("/v1/subscriptions", _SubscriptionService_ListUserSubscriptions0_HTTP_Handler(srv))
}

func _SubscriptionService_GetUserSubscription0_HTTP_Handler(srv SubscriptionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserSubscriptionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionServiceGetUserSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserSubscription(ctx, req.(*GetUserSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserSubscriptionResponse)
		return ctx.Result(200, reply)
	}
}

func _SubscriptionService_SubscribePlan0_HTTP_Handler(srv SubscriptionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubscribePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionServiceSubscribePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubscribePlan(ctx, req.(*SubscribePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubscribePlanResponse)
		return ctx.Result(200, reply)
	}
}

func _SubscriptionService_ListUserSubscriptions0_HTTP_Handler(srv SubscriptionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUserSubscriptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionServiceListUserSubscriptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserSubscriptions(ctx, req.(*ListUserSubscriptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUserSubscriptionsResponse)
		return ctx.Result(200, reply)
	}
}

type SubscriptionServiceHTTPClient interface {
	GetUserSubscription(ctx context.Context, req *GetUserSubscriptionRequest, opts ...http.CallOption) (rsp *GetUserSubscriptionResponse, err error)
	ListUserSubscriptions(ctx context.Context, req *ListUserSubscriptionsRequest, opts ...http.CallOption) (rsp *ListUserSubscriptionsResponse, err error)
	SubscribePlan(ctx context.Context, req *SubscribePlanRequest, opts ...http.CallOption) (rsp *SubscribePlanResponse, err error)
}

type SubscriptionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSubscriptionServiceHTTPClient(client *http.Client) SubscriptionServiceHTTPClient {
	return &SubscriptionServiceHTTPClientImpl{client}
}

func (c *SubscriptionServiceHTTPClientImpl) GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...http.CallOption) (*GetUserSubscriptionResponse, error) {
	var out GetUserSubscriptionResponse
	pattern := "/v1/subscriptions/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionServiceGetUserSubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SubscriptionServiceHTTPClientImpl) ListUserSubscriptions(ctx context.Context, in *ListUserSubscriptionsRequest, opts ...http.CallOption) (*ListUserSubscriptionsResponse, error) {
	var out ListUserSubscriptionsResponse
	pattern := "/v1/subscriptions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionServiceListUserSubscriptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SubscriptionServiceHTTPClientImpl) SubscribePlan(ctx context.Context, in *SubscribePlanRequest, opts ...http.CallOption) (*SubscribePlanResponse, error) {
	var out SubscribePlanResponse
	pattern := "/v1/subscriptions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionServiceSubscribePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
