syntax = "proto3";
package kratos.api;

option go_package = "server/internal/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Data data = 2;
}

message Server {
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 1;
  GRPC grpc = 2;
}

message Data {
  message Database {
    bool enable = 1;
    string driver = 2;
    string source = 3;
  }
  Database database = 1;
  message SpiceDB {
    bool enable = 1;
    string endpoint = 2;
    string token = 3;
    bool insecure = 4;
  }
  SpiceDB spicedb = 3;
  message Auth {
    string host = 1;
    string kid = 2;
    string client_id = 3;
    string client_secret = 4;
  }
  Auth auth = 4;
  message Extension {
    message Group {
      repeated string exts = 1;
      repeated string mime_types = 2;
    }
    Group photo = 1;
    Group video = 2;
    Group audio = 3;
    Group document = 4;
    Group compress = 5;
    Group other = 6;
  }
  Extension extension = 5;
}
