// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plan/v1/plan.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StorageQuota  int64                  `protobuf:"varint,3,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_plan_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *Plan) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Plan) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_plan_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanReply) Reset() {
	*x = GetPlanReply{}
	mi := &file_plan_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanReply) ProtoMessage() {}

func (x *GetPlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanReply.ProtoReflect.Descriptor instead.
func (*GetPlanReply) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlanReply) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_plan_v1_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{3}
}

type ListPlansReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansReply) Reset() {
	*x = ListPlansReply{}
	mi := &file_plan_v1_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansReply) ProtoMessage() {}

func (x *ListPlansReply) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansReply.ProtoReflect.Descriptor instead.
func (*ListPlansReply) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlansReply) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StorageQuota  int64                  `protobuf:"varint,2,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,4,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_plan_v1_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *CreatePlanRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePlanRequest) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *CreatePlanRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanReply) Reset() {
	*x = CreatePlanReply{}
	mi := &file_plan_v1_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanReply) ProtoMessage() {}

func (x *CreatePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanReply.ProtoReflect.Descriptor instead.
func (*CreatePlanReply) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePlanReply) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type UpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StorageQuota  int64                  `protobuf:"varint,3,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_plan_v1_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlanRequest) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *UpdatePlanRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdatePlanRequest) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *UpdatePlanRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpdatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanReply) Reset() {
	*x = UpdatePlanReply{}
	mi := &file_plan_v1_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanReply) ProtoMessage() {}

func (x *UpdatePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanReply.ProtoReflect.Descriptor instead.
func (*UpdatePlanReply) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePlanReply) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type DeletePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanRequest) Reset() {
	*x = DeletePlanRequest{}
	mi := &file_plan_v1_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanRequest) ProtoMessage() {}

func (x *DeletePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanRequest.ProtoReflect.Descriptor instead.
func (*DeletePlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanReply) Reset() {
	*x = DeletePlanReply{}
	mi := &file_plan_v1_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanReply) ProtoMessage() {}

func (x *DeletePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_plan_v1_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanReply.ProtoReflect.Descriptor instead.
func (*DeletePlanReply) Descriptor() ([]byte, []int) {
	return file_plan_v1_plan_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePlanReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_plan_v1_plan_proto protoreflect.FileDescriptor

const file_plan_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x12plan/v1/plan.proto\x12\vapi.plan.v1\x1a\x1cgoogle/api/annotations.proto\"\x91\x02\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rstorage_quota\x18\x03 \x01(\x03R\fstorageQuota\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x05 \x01(\x03R\rdiscountPrice\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\fGetPlanReply\x12%\n" +
	"\x04plan\x18\x01 \x01(\v2\x11.api.plan.v1.PlanR\x04plan\"\x12\n" +
	"\x10ListPlansRequest\"9\n" +
	"\x0eListPlansReply\x12'\n" +
	"\x05plans\x18\x01 \x03(\v2\x11.api.plan.v1.PlanR\x05plans\"\xd0\x01\n" +
	"\x11CreatePlanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rstorage_quota\x18\x02 \x01(\x03R\fstorageQuota\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x04 \x01(\x03R\rdiscountPrice\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"8\n" +
	"\x0fCreatePlanReply\x12%\n" +
	"\x04plan\x18\x01 \x01(\v2\x11.api.plan.v1.PlanR\x04plan\"\xe0\x01\n" +
	"\x11UpdatePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rstorage_quota\x18\x03 \x01(\x03R\fstorageQuota\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x05 \x01(\x03R\rdiscountPrice\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"8\n" +
	"\x0fUpdatePlanReply\x12%\n" +
	"\x04plan\x18\x01 \x01(\v2\x11.api.plan.v1.PlanR\x04plan\"#\n" +
	"\x11DeletePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fDeletePlanReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf1\x03\n" +
	"\vPlanService\x12Y\n" +
	"\aGetPlan\x12\x1b.api.plan.v1.GetPlanRequest\x1a\x19.api.plan.v1.GetPlanReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/plans/{id}\x12Z\n" +
	"\tListPlans\x12\x1d.api.plan.v1.ListPlansRequest\x1a\x1b.api.plan.v1.ListPlansReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/plans\x12`\n" +
	"\n" +
	"CreatePlan\x12\x1e.api.plan.v1.CreatePlanRequest\x1a\x1c.api.plan.v1.CreatePlanReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/plans\x12e\n" +
	"\n" +
	"UpdatePlan\x12\x1e.api.plan.v1.UpdatePlanRequest\x1a\x1c.api.plan.v1.UpdatePlanReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/plans/{id}\x12b\n" +
	"\n" +
	"DeletePlan\x12\x1e.api.plan.v1.DeletePlanRequest\x1a\x1c.api.plan.v1.DeletePlanReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/plans/{id}B\x15Z\x13file/api/plan/v1;v1b\x06proto3"

var (
	file_plan_v1_plan_proto_rawDescOnce sync.Once
	file_plan_v1_plan_proto_rawDescData []byte
)

func file_plan_v1_plan_proto_rawDescGZIP() []byte {
	file_plan_v1_plan_proto_rawDescOnce.Do(func() {
		file_plan_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_v1_plan_proto_rawDesc), len(file_plan_v1_plan_proto_rawDesc)))
	})
	return file_plan_v1_plan_proto_rawDescData
}

var file_plan_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plan_v1_plan_proto_goTypes = []any{
	(*Plan)(nil),              // 0: api.plan.v1.Plan
	(*GetPlanRequest)(nil),    // 1: api.plan.v1.GetPlanRequest
	(*GetPlanReply)(nil),      // 2: api.plan.v1.GetPlanReply
	(*ListPlansRequest)(nil),  // 3: api.plan.v1.ListPlansRequest
	(*ListPlansReply)(nil),    // 4: api.plan.v1.ListPlansReply
	(*CreatePlanRequest)(nil), // 5: api.plan.v1.CreatePlanRequest
	(*CreatePlanReply)(nil),   // 6: api.plan.v1.CreatePlanReply
	(*UpdatePlanRequest)(nil), // 7: api.plan.v1.UpdatePlanRequest
	(*UpdatePlanReply)(nil),   // 8: api.plan.v1.UpdatePlanReply
	(*DeletePlanRequest)(nil), // 9: api.plan.v1.DeletePlanRequest
	(*DeletePlanReply)(nil),   // 10: api.plan.v1.DeletePlanReply
}
var file_plan_v1_plan_proto_depIdxs = []int32{
	0,  // 0: api.plan.v1.GetPlanReply.plan:type_name -> api.plan.v1.Plan
	0,  // 1: api.plan.v1.ListPlansReply.plans:type_name -> api.plan.v1.Plan
	0,  // 2: api.plan.v1.CreatePlanReply.plan:type_name -> api.plan.v1.Plan
	0,  // 3: api.plan.v1.UpdatePlanReply.plan:type_name -> api.plan.v1.Plan
	1,  // 4: api.plan.v1.PlanService.GetPlan:input_type -> api.plan.v1.GetPlanRequest
	3,  // 5: api.plan.v1.PlanService.ListPlans:input_type -> api.plan.v1.ListPlansRequest
	5,  // 6: api.plan.v1.PlanService.CreatePlan:input_type -> api.plan.v1.CreatePlanRequest
	7,  // 7: api.plan.v1.PlanService.UpdatePlan:input_type -> api.plan.v1.UpdatePlanRequest
	9,  // 8: api.plan.v1.PlanService.DeletePlan:input_type -> api.plan.v1.DeletePlanRequest
	2,  // 9: api.plan.v1.PlanService.GetPlan:output_type -> api.plan.v1.GetPlanReply
	4,  // 10: api.plan.v1.PlanService.ListPlans:output_type -> api.plan.v1.ListPlansReply
	6,  // 11: api.plan.v1.PlanService.CreatePlan:output_type -> api.plan.v1.CreatePlanReply
	8,  // 12: api.plan.v1.PlanService.UpdatePlan:output_type -> api.plan.v1.UpdatePlanReply
	10, // 13: api.plan.v1.PlanService.DeletePlan:output_type -> api.plan.v1.DeletePlanReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plan_v1_plan_proto_init() }
func file_plan_v1_plan_proto_init() {
	if File_plan_v1_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_v1_plan_proto_rawDesc), len(file_plan_v1_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_v1_plan_proto_goTypes,
		DependencyIndexes: file_plan_v1_plan_proto_depIdxs,
		MessageInfos:      file_plan_v1_plan_proto_msgTypes,
	}.Build()
	File_plan_v1_plan_proto = out.File
	file_plan_v1_plan_proto_goTypes = nil
	file_plan_v1_plan_proto_depIdxs = nil
}
