// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: dashboard/v1/dashboard.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDashboardServiceGetDashboardSummary = "/dashboard.v1.DashboardService/GetDashboardSummary"

type DashboardServiceHTTPServer interface {
	GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*GetDashboardSummaryReply, error)
}

func RegisterDashboardServiceHTTPServer(s *http.Server, srv DashboardServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/dashboard/summary", _DashboardService_GetDashboardSummary0_HTTP_Handler(srv))
}

func _DashboardService_GetDashboardSummary0_HTTP_Handler(srv DashboardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDashboardSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDashboardServiceGetDashboardSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDashboardSummary(ctx, req.(*GetDashboardSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDashboardSummaryReply)
		return ctx.Result(200, reply)
	}
}

type DashboardServiceHTTPClient interface {
	GetDashboardSummary(ctx context.Context, req *GetDashboardSummaryRequest, opts ...http.CallOption) (rsp *GetDashboardSummaryReply, err error)
}

type DashboardServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDashboardServiceHTTPClient(client *http.Client) DashboardServiceHTTPClient {
	return &DashboardServiceHTTPClientImpl{client}
}

func (c *DashboardServiceHTTPClientImpl) GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...http.CallOption) (*GetDashboardSummaryReply, error) {
	var out GetDashboardSummaryReply
	pattern := "/v1/dashboard/summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDashboardServiceGetDashboardSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
