// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dashboard/v1/dashboard.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryRequest) Reset() {
	*x = GetDashboardSummaryRequest{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryRequest) ProtoMessage() {}

func (x *GetDashboardSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

type GetDashboardSummaryReply struct {
	state          protoimpl.MessageState                     `protogen:"open.v1"`
	WelcomeMessage string                                     `protobuf:"bytes,1,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	Storage        *GetDashboardSummaryReply_StorageBreakdown `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	RecentActivity []*GetDashboardSummaryReply_RecentActivity `protobuf:"bytes,3,rep,name=recent_activity,json=recentActivity,proto3" json:"recent_activity,omitempty"`
	ActivePlanName string                                     `protobuf:"bytes,4,opt,name=active_plan_name,json=activePlanName,proto3" json:"active_plan_name,omitempty"`
	TotalFiles     int64                                      `protobuf:"varint,5,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	TotalFolders   int64                                      `protobuf:"varint,6,opt,name=total_folders,json=totalFolders,proto3" json:"total_folders,omitempty"`
	TotalShared    int64                                      `protobuf:"varint,7,opt,name=total_shared,json=totalShared,proto3" json:"total_shared,omitempty"`
	Report         *GetDashboardSummaryReply_DashboardReport  `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDashboardSummaryReply) Reset() {
	*x = GetDashboardSummaryReply{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryReply) ProtoMessage() {}

func (x *GetDashboardSummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryReply.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryReply) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardSummaryReply) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

func (x *GetDashboardSummaryReply) GetStorage() *GetDashboardSummaryReply_StorageBreakdown {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *GetDashboardSummaryReply) GetRecentActivity() []*GetDashboardSummaryReply_RecentActivity {
	if x != nil {
		return x.RecentActivity
	}
	return nil
}

func (x *GetDashboardSummaryReply) GetActivePlanName() string {
	if x != nil {
		return x.ActivePlanName
	}
	return ""
}

func (x *GetDashboardSummaryReply) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *GetDashboardSummaryReply) GetTotalFolders() int64 {
	if x != nil {
		return x.TotalFolders
	}
	return 0
}

func (x *GetDashboardSummaryReply) GetTotalShared() int64 {
	if x != nil {
		return x.TotalShared
	}
	return 0
}

func (x *GetDashboardSummaryReply) GetReport() *GetDashboardSummaryReply_DashboardReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetDashboardSummaryReply_StorageBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photos        int64                  `protobuf:"varint,1,opt,name=photos,proto3" json:"photos,omitempty"`
	Videos        int64                  `protobuf:"varint,2,opt,name=videos,proto3" json:"videos,omitempty"`
	Documents     int64                  `protobuf:"varint,3,opt,name=documents,proto3" json:"documents,omitempty"`
	Audio         int64                  `protobuf:"varint,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Compress      int64                  `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
	Other         int64                  `protobuf:"varint,6,opt,name=other,proto3" json:"other,omitempty"`
	Total         int64                  `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	Quota         int64                  `protobuf:"varint,8,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryReply_StorageBreakdown) Reset() {
	*x = GetDashboardSummaryReply_StorageBreakdown{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryReply_StorageBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryReply_StorageBreakdown) ProtoMessage() {}

func (x *GetDashboardSummaryReply_StorageBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryReply_StorageBreakdown.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryReply_StorageBreakdown) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetPhotos() int64 {
	if x != nil {
		return x.Photos
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetVideos() int64 {
	if x != nil {
		return x.Videos
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetDocuments() int64 {
	if x != nil {
		return x.Documents
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetAudio() int64 {
	if x != nil {
		return x.Audio
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetCompress() int64 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetOther() int64 {
	if x != nil {
		return x.Other
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDashboardSummaryReply_StorageBreakdown) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

type GetDashboardSummaryReply_RecentActivity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Icon           string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Size           string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	LastAccessedAt string                 `protobuf:"bytes,6,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	IsFolder       bool                   `protobuf:"varint,7,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDashboardSummaryReply_RecentActivity) Reset() {
	*x = GetDashboardSummaryReply_RecentActivity{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryReply_RecentActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryReply_RecentActivity) ProtoMessage() {}

func (x *GetDashboardSummaryReply_RecentActivity) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryReply_RecentActivity.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryReply_RecentActivity) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetDashboardSummaryReply_RecentActivity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetLastAccessedAt() string {
	if x != nil {
		return x.LastAccessedAt
	}
	return ""
}

func (x *GetDashboardSummaryReply_RecentActivity) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

type GetDashboardSummaryReply_DashboardReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewFilesCount  int64                  `protobuf:"varint,1,opt,name=new_files_count,json=newFilesCount,proto3" json:"new_files_count,omitempty"`
	NewStorageUsed int64                  `protobuf:"varint,2,opt,name=new_storage_used,json=newStorageUsed,proto3" json:"new_storage_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDashboardSummaryReply_DashboardReport) Reset() {
	*x = GetDashboardSummaryReply_DashboardReport{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryReply_DashboardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryReply_DashboardReport) ProtoMessage() {}

func (x *GetDashboardSummaryReply_DashboardReport) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryReply_DashboardReport.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryReply_DashboardReport) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GetDashboardSummaryReply_DashboardReport) GetNewFilesCount() int64 {
	if x != nil {
		return x.NewFilesCount
	}
	return 0
}

func (x *GetDashboardSummaryReply_DashboardReport) GetNewStorageUsed() int64 {
	if x != nil {
		return x.NewStorageUsed
	}
	return 0
}

var File_dashboard_v1_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1cdashboard/v1/dashboard.proto\x12\fdashboard.v1\x1a\x1cgoogle/api/annotations.proto\"\x1c\n" +
	"\x1aGetDashboardSummaryRequest\"\xcf\a\n" +
	"\x18GetDashboardSummaryReply\x12'\n" +
	"\x0fwelcome_message\x18\x01 \x01(\tR\x0ewelcomeMessage\x12Q\n" +
	"\astorage\x18\x02 \x01(\v27.dashboard.v1.GetDashboardSummaryReply.StorageBreakdownR\astorage\x12^\n" +
	"\x0frecent_activity\x18\x03 \x03(\v25.dashboard.v1.GetDashboardSummaryReply.RecentActivityR\x0erecentActivity\x12(\n" +
	"\x10active_plan_name\x18\x04 \x01(\tR\x0eactivePlanName\x12\x1f\n" +
	"\vtotal_files\x18\x05 \x01(\x03R\n" +
	"totalFiles\x12#\n" +
	"\rtotal_folders\x18\x06 \x01(\x03R\ftotalFolders\x12!\n" +
	"\ftotal_shared\x18\a \x01(\x03R\vtotalShared\x12N\n" +
	"\x06report\x18\b \x01(\v26.dashboard.v1.GetDashboardSummaryReply.DashboardReportR\x06report\x1a\xd4\x01\n" +
	"\x10StorageBreakdown\x12\x16\n" +
	"\x06photos\x18\x01 \x01(\x03R\x06photos\x12\x16\n" +
	"\x06videos\x18\x02 \x01(\x03R\x06videos\x12\x1c\n" +
	"\tdocuments\x18\x03 \x01(\x03R\tdocuments\x12\x14\n" +
	"\x05audio\x18\x04 \x01(\x03R\x05audio\x12\x1a\n" +
	"\bcompress\x18\x05 \x01(\x03R\bcompress\x12\x14\n" +
	"\x05other\x18\x06 \x01(\x03R\x05other\x12\x14\n" +
	"\x05total\x18\a \x01(\x03R\x05total\x12\x14\n" +
	"\x05quota\x18\b \x01(\x03R\x05quota\x1a\xb7\x01\n" +
	"\x0eRecentActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12(\n" +
	"\x10last_accessed_at\x18\x06 \x01(\tR\x0elastAccessedAt\x12\x1b\n" +
	"\tis_folder\x18\a \x01(\bR\bisFolder\x1ac\n" +
	"\x0fDashboardReport\x12&\n" +
	"\x0fnew_files_count\x18\x01 \x01(\x03R\rnewFilesCount\x12(\n" +
	"\x10new_storage_used\x18\x02 \x01(\x03R\x0enewStorageUsed2\x9b\x01\n" +
	"\x10DashboardService\x12\x86\x01\n" +
	"\x13GetDashboardSummary\x12(.dashboard.v1.GetDashboardSummaryRequest\x1a&.dashboard.v1.GetDashboardSummaryReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/dashboard/summaryB\x1aZ\x18file/api/dashboard/v1;v1b\x06proto3"

var (
	file_dashboard_v1_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_v1_dashboard_proto_rawDescData []byte
)

func file_dashboard_v1_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)))
	})
	return file_dashboard_v1_dashboard_proto_rawDescData
}

var file_dashboard_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dashboard_v1_dashboard_proto_goTypes = []any{
	(*GetDashboardSummaryRequest)(nil),                // 0: dashboard.v1.GetDashboardSummaryRequest
	(*GetDashboardSummaryReply)(nil),                  // 1: dashboard.v1.GetDashboardSummaryReply
	(*GetDashboardSummaryReply_StorageBreakdown)(nil), // 2: dashboard.v1.GetDashboardSummaryReply.StorageBreakdown
	(*GetDashboardSummaryReply_RecentActivity)(nil),   // 3: dashboard.v1.GetDashboardSummaryReply.RecentActivity
	(*GetDashboardSummaryReply_DashboardReport)(nil),  // 4: dashboard.v1.GetDashboardSummaryReply.DashboardReport
}
var file_dashboard_v1_dashboard_proto_depIdxs = []int32{
	2, // 0: dashboard.v1.GetDashboardSummaryReply.storage:type_name -> dashboard.v1.GetDashboardSummaryReply.StorageBreakdown
	3, // 1: dashboard.v1.GetDashboardSummaryReply.recent_activity:type_name -> dashboard.v1.GetDashboardSummaryReply.RecentActivity
	4, // 2: dashboard.v1.GetDashboardSummaryReply.report:type_name -> dashboard.v1.GetDashboardSummaryReply.DashboardReport
	0, // 3: dashboard.v1.DashboardService.GetDashboardSummary:input_type -> dashboard.v1.GetDashboardSummaryRequest
	1, // 4: dashboard.v1.DashboardService.GetDashboardSummary:output_type -> dashboard.v1.GetDashboardSummaryReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dashboard_v1_dashboard_proto_init() }
func file_dashboard_v1_dashboard_proto_init() {
	if File_dashboard_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_v1_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_v1_dashboard_proto = out.File
	file_dashboard_v1_dashboard_proto_goTypes = nil
	file_dashboard_v1_dashboard_proto_depIdxs = nil
}
