// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: permission/v1/permission.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPermissionServiceCheckPermission = "/permission.v1.PermissionService/CheckPermission"
const OperationPermissionServiceDeleteRelationship = "/permission.v1.PermissionService/DeleteRelationship"
const OperationPermissionServiceSwapRelationship = "/permission.v1.PermissionService/SwapRelationship"
const OperationPermissionServiceWriteRelationship = "/permission.v1.PermissionService/WriteRelationship"

type PermissionServiceHTTPServer interface {
	// CheckPermission Internal API: Asks SpiceDB if a subject can perform an action
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionReply, error)
	DeleteRelationship(context.Context, *DeleteRelationshipRequest) (*DeleteRelationshipReply, error)
	SwapRelationship(context.Context, *SwapRelationshipRequest) (*SwapRelationshipReply, error)
	// WriteRelationship Internal API: Tells SpiceDB to create a new ownership/parent tuple
	WriteRelationship(context.Context, *WriteRelationshipRequest) (*WriteRelationshipReply, error)
}

func RegisterPermissionServiceHTTPServer(s *http.Server, srv PermissionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/internal/permissions/check", _PermissionService_CheckPermission0_HTTP_Handler(srv))
	r.POST("/v1/internal/permissions/write", _PermissionService_WriteRelationship0_HTTP_Handler(srv))
	r.POST("/v1/internal/permissions/delete", _PermissionService_DeleteRelationship0_HTTP_Handler(srv))
	r.POST("/v1/internal/permissions/swap", _PermissionService_SwapRelationship0_HTTP_Handler(srv))
}

func _PermissionService_CheckPermission0_HTTP_Handler(srv PermissionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckPermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionServiceCheckPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckPermission(ctx, req.(*CheckPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckPermissionReply)
		return ctx.Result(200, reply)
	}
}

func _PermissionService_WriteRelationship0_HTTP_Handler(srv PermissionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WriteRelationshipRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionServiceWriteRelationship)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WriteRelationship(ctx, req.(*WriteRelationshipRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WriteRelationshipReply)
		return ctx.Result(200, reply)
	}
}

func _PermissionService_DeleteRelationship0_HTTP_Handler(srv PermissionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRelationshipRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionServiceDeleteRelationship)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRelationship(ctx, req.(*DeleteRelationshipRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRelationshipReply)
		return ctx.Result(200, reply)
	}
}

func _PermissionService_SwapRelationship0_HTTP_Handler(srv PermissionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SwapRelationshipRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionServiceSwapRelationship)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SwapRelationship(ctx, req.(*SwapRelationshipRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SwapRelationshipReply)
		return ctx.Result(200, reply)
	}
}

type PermissionServiceHTTPClient interface {
	// CheckPermission Internal API: Asks SpiceDB if a subject can perform an action
	CheckPermission(ctx context.Context, req *CheckPermissionRequest, opts ...http.CallOption) (rsp *CheckPermissionReply, err error)
	DeleteRelationship(ctx context.Context, req *DeleteRelationshipRequest, opts ...http.CallOption) (rsp *DeleteRelationshipReply, err error)
	SwapRelationship(ctx context.Context, req *SwapRelationshipRequest, opts ...http.CallOption) (rsp *SwapRelationshipReply, err error)
	// WriteRelationship Internal API: Tells SpiceDB to create a new ownership/parent tuple
	WriteRelationship(ctx context.Context, req *WriteRelationshipRequest, opts ...http.CallOption) (rsp *WriteRelationshipReply, err error)
}

type PermissionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPermissionServiceHTTPClient(client *http.Client) PermissionServiceHTTPClient {
	return &PermissionServiceHTTPClientImpl{client}
}

// CheckPermission Internal API: Asks SpiceDB if a subject can perform an action
func (c *PermissionServiceHTTPClientImpl) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...http.CallOption) (*CheckPermissionReply, error) {
	var out CheckPermissionReply
	pattern := "/v1/internal/permissions/check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionServiceCheckPermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PermissionServiceHTTPClientImpl) DeleteRelationship(ctx context.Context, in *DeleteRelationshipRequest, opts ...http.CallOption) (*DeleteRelationshipReply, error) {
	var out DeleteRelationshipReply
	pattern := "/v1/internal/permissions/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionServiceDeleteRelationship))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PermissionServiceHTTPClientImpl) SwapRelationship(ctx context.Context, in *SwapRelationshipRequest, opts ...http.CallOption) (*SwapRelationshipReply, error) {
	var out SwapRelationshipReply
	pattern := "/v1/internal/permissions/swap"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionServiceSwapRelationship))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WriteRelationship Internal API: Tells SpiceDB to create a new ownership/parent tuple
func (c *PermissionServiceHTTPClientImpl) WriteRelationship(ctx context.Context, in *WriteRelationshipRequest, opts ...http.CallOption) (*WriteRelationshipReply, error) {
	var out WriteRelationshipReply
	pattern := "/v1/internal/permissions/write"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionServiceWriteRelationship))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
