// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: permission/v1/permission.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectType   string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`    // e.g., "user"
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`          // e.g., "123"
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                             // e.g., "writer" or "owner"
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "folder" or "file"
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // e.g., "folder-789"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckPermissionRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckPermissionRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckPermissionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckPermissionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type CheckPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"` // true if access is granted, false otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReply) Reset() {
	*x = CheckPermissionReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReply) ProtoMessage() {}

func (x *CheckPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReply.ProtoReflect.Descriptor instead.
func (*CheckPermissionReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionReply) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type WriteRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "file"
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // e.g., "file-999"
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                             // e.g., "owner" or "parent"
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`    // e.g., "user" or "folder"
	SubjectId     string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`          // e.g., "123" or "folder-789"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRelationshipRequest) Reset() {
	*x = WriteRelationshipRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipRequest) ProtoMessage() {}

func (x *WriteRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipRequest.ProtoReflect.Descriptor instead.
func (*WriteRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRelationshipRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *WriteRelationshipRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *WriteRelationshipRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *WriteRelationshipRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *WriteRelationshipRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type WriteRelationshipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRelationshipReply) Reset() {
	*x = WriteRelationshipReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipReply) ProtoMessage() {}

func (x *WriteRelationshipReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipReply.ProtoReflect.Descriptor instead.
func (*WriteRelationshipReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRelationshipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "file"
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // e.g., "file-999"
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                             // e.g., "owner" or "parent"
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`    // e.g., "user" or "folder"
	SubjectId     string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`          // e.g., "123" or "folder-789"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipRequest) Reset() {
	*x = DeleteRelationshipRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipRequest) ProtoMessage() {}

func (x *DeleteRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRelationshipRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *DeleteRelationshipRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DeleteRelationshipRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *DeleteRelationshipRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *DeleteRelationshipRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type DeleteRelationshipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipReply) Reset() {
	*x = DeleteRelationshipReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipReply) ProtoMessage() {}

func (x *DeleteRelationshipReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipReply.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRelationshipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SwapRelationshipRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ResourceType string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "file" or "folder"
	ResourceId   string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // e.g., "789-abc-..."
	// The actor stays exactly the same
	SubjectType string `protobuf:"bytes,3,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"` // e.g., "share_link" (or "user")
	SubjectId   string `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`       // e.g., "V1StGXR8_Z5jdHi6B-myT"
	// The permission is what gets swapped
	OldRelation   string `protobuf:"bytes,5,opt,name=old_relation,json=oldRelation,proto3" json:"old_relation,omitempty"` // e.g., "viewer"
	NewRelation   string `protobuf:"bytes,6,opt,name=new_relation,json=newRelation,proto3" json:"new_relation,omitempty"` // e.g., "editor"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapRelationshipRequest) Reset() {
	*x = SwapRelationshipRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapRelationshipRequest) ProtoMessage() {}

func (x *SwapRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapRelationshipRequest.ProtoReflect.Descriptor instead.
func (*SwapRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *SwapRelationshipRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SwapRelationshipRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SwapRelationshipRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SwapRelationshipRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SwapRelationshipRequest) GetOldRelation() string {
	if x != nil {
		return x.OldRelation
	}
	return ""
}

func (x *SwapRelationshipRequest) GetNewRelation() string {
	if x != nil {
		return x.NewRelation
	}
	return ""
}

type SwapRelationshipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapRelationshipReply) Reset() {
	*x = SwapRelationshipReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapRelationshipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapRelationshipReply) ProtoMessage() {}

func (x *SwapRelationshipReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapRelationshipReply.ProtoReflect.Descriptor instead.
func (*SwapRelationshipReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *SwapRelationshipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_permission_v1_permission_proto protoreflect.FileDescriptor

const file_permission_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1epermission/v1/permission.proto\x12\rpermission.v1\x1a\x1cgoogle/api/annotations.proto\"\xbc\x01\n" +
	"\x16CheckPermissionRequest\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\"0\n" +
	"\x14CheckPermissionReply\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"\xbe\x01\n" +
	"\x18WriteRelationshipRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\"2\n" +
	"\x16WriteRelationshipReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbf\x01\n" +
	"\x19DeleteRelationshipRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\"3\n" +
	"\x17DeleteRelationshipReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe7\x01\n" +
	"\x17SwapRelationshipRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fsubject_type\x18\x03 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12!\n" +
	"\fold_relation\x18\x05 \x01(\tR\voldRelation\x12!\n" +
	"\fnew_relation\x18\x06 \x01(\tR\vnewRelation\"1\n" +
	"\x15SwapRelationshipReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd1\x04\n" +
	"\x11PermissionService\x12\x88\x01\n" +
	"\x0fCheckPermission\x12%.permission.v1.CheckPermissionRequest\x1a#.permission.v1.CheckPermissionReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/internal/permissions/check\x12\x8e\x01\n" +
	"\x11WriteRelationship\x12'.permission.v1.WriteRelationshipRequest\x1a%.permission.v1.WriteRelationshipReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/internal/permissions/write\x12\x92\x01\n" +
	"\x12DeleteRelationship\x12(.permission.v1.DeleteRelationshipRequest\x1a&.permission.v1.DeleteRelationshipReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/internal/permissions/delete\x12\x8a\x01\n" +
	"\x10SwapRelationship\x12&.permission.v1.SwapRelationshipRequest\x1a$.permission.v1.SwapRelationshipReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/internal/permissions/swapB Z\x1eauth_storage/api/permission/v1b\x06proto3"

var (
	file_permission_v1_permission_proto_rawDescOnce sync.Once
	file_permission_v1_permission_proto_rawDescData []byte
)

func file_permission_v1_permission_proto_rawDescGZIP() []byte {
	file_permission_v1_permission_proto_rawDescOnce.Do(func() {
		file_permission_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)))
	})
	return file_permission_v1_permission_proto_rawDescData
}

var file_permission_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_permission_v1_permission_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),    // 0: permission.v1.CheckPermissionRequest
	(*CheckPermissionReply)(nil),      // 1: permission.v1.CheckPermissionReply
	(*WriteRelationshipRequest)(nil),  // 2: permission.v1.WriteRelationshipRequest
	(*WriteRelationshipReply)(nil),    // 3: permission.v1.WriteRelationshipReply
	(*DeleteRelationshipRequest)(nil), // 4: permission.v1.DeleteRelationshipRequest
	(*DeleteRelationshipReply)(nil),   // 5: permission.v1.DeleteRelationshipReply
	(*SwapRelationshipRequest)(nil),   // 6: permission.v1.SwapRelationshipRequest
	(*SwapRelationshipReply)(nil),     // 7: permission.v1.SwapRelationshipReply
}
var file_permission_v1_permission_proto_depIdxs = []int32{
	0, // 0: permission.v1.PermissionService.CheckPermission:input_type -> permission.v1.CheckPermissionRequest
	2, // 1: permission.v1.PermissionService.WriteRelationship:input_type -> permission.v1.WriteRelationshipRequest
	4, // 2: permission.v1.PermissionService.DeleteRelationship:input_type -> permission.v1.DeleteRelationshipRequest
	6, // 3: permission.v1.PermissionService.SwapRelationship:input_type -> permission.v1.SwapRelationshipRequest
	1, // 4: permission.v1.PermissionService.CheckPermission:output_type -> permission.v1.CheckPermissionReply
	3, // 5: permission.v1.PermissionService.WriteRelationship:output_type -> permission.v1.WriteRelationshipReply
	5, // 6: permission.v1.PermissionService.DeleteRelationship:output_type -> permission.v1.DeleteRelationshipReply
	7, // 7: permission.v1.PermissionService.SwapRelationship:output_type -> permission.v1.SwapRelationshipReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permission_v1_permission_proto_init() }
func file_permission_v1_permission_proto_init() {
	if File_permission_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_v1_permission_proto_goTypes,
		DependencyIndexes: file_permission_v1_permission_proto_depIdxs,
		MessageInfos:      file_permission_v1_permission_proto_msgTypes,
	}.Build()
	File_permission_v1_permission_proto = out.File
	file_permission_v1_permission_proto_goTypes = nil
	file_permission_v1_permission_proto_depIdxs = nil
}
