server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

data:
  database:
    enable: true
    driver: pgx
    source: ${DATA_DATABASE_SOURCE:postgres://anhle:anhle@localhost:54321/file_storage?sslmode=disable}
  auth:
    host: ${DATA_AUTH_HOST:localhost:9000}
    kid: 484a19bafc6671c073a97b6bd31f069e
    client_id: file-service
    client_secret: adfa7db134a6909f609b1836fbe5eca6a84dc4537cf3b0a09c812fb1b1f35fdd

  extension:
    photo:
      exts:
        [
          ".jpg",
          ".jpeg",
          ".png",
          ".gif",
          ".bmp",
          ".tiff",
          ".tif",
          ".svg",
          ".gif",
          ".webp",
          ".heic",
          ".heif",
          ".avif",
          ".ico",
          ".psd",
          ".ai",
          ".indd",
          ".emf",
          ".wmf",
        ]
    mime_types: ["image/*"]
    video:
      exts:
        [
          ".mp4",
          ".avi",
          ".mov",
          ".wmv",
          ".flv",
          ".mkv",
          ".webm",
          ".m3u8",
          ".mpeg",
          ".3gp",
          ".m4v",
          ".ts",
          ".vob",
          ".rm",
          ".rmvb",
          ".f4v",
        ]
      mime_types: ["video/*"]
    audio:
      exts:
        [
          ".mp3",
          ".wav",
          ".aac",
          ".flac",
          ".ogg",
          ".m4a",
          ".amr",
          ".aiff",
          ".opus",
        ]
      mime_types: ["audio/*"]
    document:
      exts:
        [
          ".pdf",
          ".doc",
          ".docx",
          ".xls",
          ".xlsx",
          ".ppt",
          ".pptx",
          ".txt",
          ".csv",
          ".odt",
          ".rtf",
          ".pages",
          ".epub",
          ".md",
          ".xml",
          ".json",
          ".html",
          ".htm",
          ".pptm",
          ".docm",
          ".ods",
          ".xltx",
          ".xltm",
          ".dotx",
          ".dotm",
        ]
      mime_types:
        [
          "application/pdf",
          "application/msword",
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "application/vnd.ms-excel",
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "application/vnd.ms-powerpoint",
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "application/vnd.oasis.opendocument.text",
          "application/rtf",
          "application/epub+zip",
          "application/vnd.ms-powerpoint",
          "application/vnd.ms-excel",
          "application/vnd.oasis.opendocument.spreadsheet",
          "application/vnd.oasis.opendocument.presentation",
          "application/xml",
          "application/json",
          "text/plain",
          "text/csv",
          "text/markdown",
          "text/html",
          "text/javascript",
        ]
    compress:
      exts:
        [
          ".zip",
          ".rar",
          ".7z",
          ".tar",
          ".gz",
          ".z",
          ".bz2",
          ".z",
          ".tar.bz2",
          ".tar.xz",
          ".tar.zst",
          ".tar.gz",
          ".tgz",
          ".zst",
          ".lz4",
          ".lzo",
          ".rar5",
          ".cab",
          ".arj",
          ".ace",
          ".apk",
        ]
      mime_types:
        [
          "application/zip",
          "application/x-rar-compressed",
          "application/x-7z-compressed",
          "application/x-tar",
          "application/gzip",
          "application/x-bzip2",
          "application/x-zstd",
          "application/x-lz4",
          "application/x-lzo",
          "application/x-rar",
          "application/vnd.ms-cab-compressed",
          "application/x-arj",
          "application/x-ace",
          "application/vnd.android.package-archive",
        ]
    other:
      exts: []
      mime_types: []

  sharing:
    base_url: "https://besanh.com/s/"

  s3:
    endpoint: "https://s3.ap-southeast-1.amazonaws.com"
    access_key: ""
    secret_key: ""
    bucket: "anhle-file-storage"
    use_ssl: true
    region: "ap-southeast-1"
    public_access: false
