// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"file/internal/biz"
	"file/internal/conf"
	"file/internal/data"
	"file/internal/server"
	"file/internal/service"
	"file/internal/util"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData, logger)
	physicalFileRepo := data.NewPhysicalFileRepo(dataData, logger)
	authRepo, err := data.NewAuthRepo(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	transaction := data.NewTransactionManager(dataData)
	fileUsecase := biz.NewFileUsecase(fileRepo, physicalFileRepo, authRepo, transaction, logger)
	fileService := service.NewFileService(fileUsecase)
	publicPEM, err := util.NewPublicPEM(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publicKey, err := biz.NewPublicKey(publicPEM)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, confData, fileService, logger, publicKey)
	httpServer := server.NewHTTPServer(confServer, confData, fileService, logger, publicKey)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
